-- ============================================
-- 수익성분석 검증용 테이블 DDL
-- Source: ZOHCO004_2405_240701
-- DB: company_board
-- Table: MOD_BOARD_PROFIT_ANALYSIS
-- ============================================

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

USE company_board;

DROP TABLE IF EXISTS MOD_BOARD_PROFIT_ANALYSIS;

CREATE TABLE MOD_BOARD_PROFIT_ANALYSIS (
    SEQ         BIGINT       NOT NULL AUTO_INCREMENT COMMENT '일련번호',
    CALMONTH             VARCHAR(10)          NULL     COMMENT '달력연도/월',
    CALDAY               VARCHAR(10)          NULL     COMMENT '달력일',
    CO_AREA              VARCHAR(10)          NULL     COMMENT '관리회계 영역',
    PROFIT_CTR           VARCHAR(20)          NULL     COMMENT '손익 센터',
    DIVISION             VARCHAR(5)           NULL     COMMENT '제품군',
    PLANT                VARCHAR(10)          NULL     COMMENT '플랜트',
    DISTR_CHAN           VARCHAR(5)           NULL     COMMENT '유통 경로',
    ZDISTCHAN            VARCHAR(5)           NULL     COMMENT '내수/수출구분자(사업장)',
    ZORG_TEAM            VARCHAR(10)          NULL     COMMENT '영업팀(사업장그룹)',
    SALES_OFF            VARCHAR(10)          NULL     COMMENT '사업장',
    MATL_TYPE            VARCHAR(10)          NULL     COMMENT '자재유형',
    MATL_GROUP           VARCHAR(10)          NULL     COMMENT '자재 그룹',
    PRODH1               VARCHAR(10)          NULL     COMMENT '제품계층 구조레벨 1',
    PRODH2               VARCHAR(10)          NULL     COMMENT '제품 계층구조레벨 2',
    PRODH3               VARCHAR(15)          NULL     COMMENT '제품 계층구조레벨 3',
    PRODH4               VARCHAR(20)          NULL     COMMENT '제품 계층구조레벨 4',
    ZJPCODE              VARCHAR(10)          NULL     COMMENT '지종/제품구분',
    ZBRAND1              VARCHAR(10)          NULL     COMMENT '브랜드 1',
    ZBRAND2              VARCHAR(10)          NULL     COMMENT '브랜드 2',
    BILL_TYPE            VARCHAR(10)          NULL     COMMENT '대금청구유형',
    INCOTERMS            VARCHAR(5)           NULL     COMMENT '인도 조건',
    CUST_GROUP           VARCHAR(5)           NULL     COMMENT '고객 그룹',
    CUST_GRP1            VARCHAR(5)           NULL     COMMENT '고객 그룹 1',
    COUNTRY              VARCHAR(5)           NULL     COMMENT '국가',
    ZKUNN2               VARCHAR(20)          NULL     COMMENT '영업사원',
    CUSTOMER             VARCHAR(20)          NULL     COMMENT '고객',
    MATERIAL             VARCHAR(30)          NULL     COMMENT '자재',
    MATERIAL_DESC        VARCHAR(100)         NULL     COMMENT '자재명',
    ZUNITBOX             VARCHAR(5)           NULL     COMMENT '수량단위(BOX)',
    ZUNITBAG             VARCHAR(5)           NULL     COMMENT '수량단위(BAG)',
    ZUNITKGEA            VARCHAR(5)           NULL     COMMENT '수량단위(KG/EA)',
    CURRENCY             VARCHAR(5)           NULL     COMMENT '통화',
    ZQTYBOX              DECIMAL(18,3)        NULL     COMMENT '수량(BOX)',
    ZQTYBAG              BIGINT               NULL     COMMENT '수량(BAG)',
    ZQTYKGEA             DECIMAL(18,3)        NULL     COMMENT '수량(KG/EA)',
    ZAMT001              BIGINT               NULL     COMMENT '총매출',
    ZAMT002              BIGINT               NULL     COMMENT '판매장려금',
    ZAMT003              BIGINT               NULL     COMMENT '순매출',
    ZAMT004              BIGINT               NULL     COMMENT '기타매출',
    ZAMT005              BIGINT               NULL     COMMENT '매출원가(제품)',
    ZAMT006              BIGINT               NULL     COMMENT '재료비-펄프',
    ZAMT007              BIGINT               NULL     COMMENT '재료비-고지',
    ZAMT008              BIGINT               NULL     COMMENT '재료비-패드',
    ZAMT009              BIGINT               NULL     COMMENT '부재료비-약품',
    ZAMT010              BIGINT               NULL     COMMENT '부재료비-포장재',
    ZAMT011              BIGINT               NULL     COMMENT '재료비-기타',
    ZAMT012              BIGINT               NULL     COMMENT '인건비',
    ZAMT013              BIGINT               NULL     COMMENT '인건비_경비',
    ZAMT014              BIGINT               NULL     COMMENT '인건비_기타',
    ZAMT015              BIGINT               NULL     COMMENT '도급비',
    ZAMT016              BIGINT               NULL     COMMENT '에너지비',
    ZAMT017              BIGINT               NULL     COMMENT '전력비',
    ZAMT018              BIGINT               NULL     COMMENT '감가상각비',
    ZAMT019              BIGINT               NULL     COMMENT '수선/소모품비',
    ZAMT020              BIGINT               NULL     COMMENT '기타경비',
    ZAMT021              BIGINT               NULL     COMMENT '기타경비_폐기물',
    ZAMT022              BIGINT               NULL     COMMENT '기타경비_세금과공과',
    ZAMT023              BIGINT               NULL     COMMENT '기타경비_지급수수료',
    ZAMT024              BIGINT               NULL     COMMENT '외주가공비',
    ZAMT025              BIGINT               NULL     COMMENT '매출원가(상품)',
    ZAMT026              BIGINT               NULL     COMMENT '매출원가(기타)',
    ZAMT027              BIGINT               NULL     COMMENT '기타원가',
    ZAMT028              BIGINT               NULL     COMMENT '단수차이',
    ZAMT029              BIGINT               NULL     COMMENT '차이잔액',
    ZAMT030              BIGINT               NULL     COMMENT '제조파지정산',
    ZAMT031              BIGINT               NULL     COMMENT '기타매출원가+감모손+평가손',
    ZAMT032              BIGINT               NULL     COMMENT '원재료 투입차이',
    ZAMT033              BIGINT               NULL     COMMENT '기타매출원가 배부조',
    ZAMT034              BIGINT               NULL     COMMENT '매출원가 계',
    ZAMT035              BIGINT               NULL     COMMENT '매출총이익',
    ZAMT036              BIGINT               NULL     COMMENT '판매관리비',
    ZAMT037              BIGINT               NULL     COMMENT '급여(변동)',
    ZAMT038              BIGINT               NULL     COMMENT '국내운반비(변동)',
    ZAMT039              BIGINT               NULL     COMMENT '수출운반비(변동)',
    ZAMT040              BIGINT               NULL     COMMENT '지급수수료(변동)',
    ZAMT041              BIGINT               NULL     COMMENT '기타판관비(변동)',
    ZAMT042              BIGINT               NULL     COMMENT '개발비(변동)',
    ZAMT043              BIGINT               NULL     COMMENT '급여(고정)',
    ZAMT044              BIGINT               NULL     COMMENT '지급수수료(고정)',
    ZAMT045              BIGINT               NULL     COMMENT '기타판관비(고정)',
    ZAMT046              BIGINT               NULL     COMMENT '개발비(고정)',
    ZAMT047              BIGINT               NULL     COMMENT '마케팅비',
    ZAMT048              BIGINT               NULL     COMMENT '광고비',
    ZAMT049              BIGINT               NULL     COMMENT '소모품비',
    ZAMT050              BIGINT               NULL     COMMENT '지급수수료-마케팅(변동)',
    ZAMT051              BIGINT               NULL     COMMENT '지급수수료-마케팅(고정)',
    ZAMT052              BIGINT               NULL     COMMENT '마케팅비_장려금(변동)',
    ZAMT053              BIGINT               NULL     COMMENT '판촉비',
    ZAMT054              BIGINT               NULL     COMMENT '마케팅비 배부조정',
    ZAMT055              BIGINT               NULL     COMMENT '영업이익',
    ZAMT056              BIGINT               NULL     COMMENT '영업외수익',
    ZAMT057              BIGINT               NULL     COMMENT '이자수익',
    ZAMT058              BIGINT               NULL     COMMENT '외환이익',
    ZAMT059              BIGINT               NULL     COMMENT '기타영업외수익',
    ZAMT060              BIGINT               NULL     COMMENT '영업외비용',
    ZAMT061              BIGINT               NULL     COMMENT '이자비용',
    ZAMT062              BIGINT               NULL     COMMENT '외환손실',
    ZAMT063              BIGINT               NULL     COMMENT '기타영업외비용',
    ZAMT064              BIGINT               NULL     COMMENT '경상이익',
    PRIMARY KEY (SEQ),
    INDEX IDX_PROFIT_CALMONTH (CALMONTH),
    INDEX IDX_PROFIT_CALDAY (CALDAY),
    INDEX IDX_PROFIT_PROFIT_CTR (PROFIT_CTR),
    INDEX IDX_PROFIT_MATERIAL (MATERIAL),
    INDEX IDX_PROFIT_CUSTOMER (CUSTOMER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='수익성분석 검증용 데이터 (ZOHCO004_2405_240701)';